on: 
  push:
    paths:
      - 'example/**'
      - 'metascore/**'
      - 'src/**'
      - 'test/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.2
        with:
          dfx-version: 0.8.1
          install-moc: true
          vessel-version: 0.6.2
      - run: for i in example/*.mo ; do moc $(vessel sources) --check $i ; done
      - run: for i in metascore/*.mo ; do moc $(vessel sources) --check $i ; done
      - run: for i in src/*.mo ; do moc $(vessel sources) --check $i ; done
      - run: for i in test/*.mo ; do moc $(vessel sources) -r $i ; done
